//
// Created by abdullah on 29/05/2017.
//

#ifndef SIMULATION_1_SLIDINGWIRECONSTRAINT_H
#define SIMULATION_1_SLIDINGWIRECONSTRAINT_H


class SlidingWireConstraint {

};


#endif //SIMULATION_1_SLIDINGWIRECONSTRAINT_H
